site_name: Qihang's Blog For Learning Systems

site_url: https://qihang-zhang.github.io/Learning-Sys-Blog

extra:
  homepage: https://qihang-zhang.github.io/

plugins:
  - blog:
      blog_dir: Blog
      blog_toc: true
      post_dir: "{blog}/Posts"

theme:
  logo: assets/fruit/watermelon.svg
  favicon: assets/fruit/lemon.svg